# Generated by Django 4.1.2 on 2022-10-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_stock_prevclose'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Selling',
            field=models.BooleanField(default=False),
        ),
    ]
