# Generated by Django 4.1.2 on 2022-10-31 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_property_selling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Selling',
            new_name='selling',
        ),
    ]
