# Generated by Django 4.1.2 on 2022-11-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_transaction_seller_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='item_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='itemType',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
