# Generated by Django 4.1.2 on 2022-11-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_transaction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='shares',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
